PROXY="lmancuso@130.192.137.199"
CERT_PATH="/home/lore/Scaricati/mancuso_federated"

RESET_COMMAND="cd federated-learning/Client/snapshots; rm -rfv ./*"

#ssh -i $CERT_PATH -J $PROXY lmancuso@coordinator "cd federated-learning/Server/snapshots/ ; rm -rfv ./*"
#
#ssh -i $CERT_PATH -J $PROXY lmancuso@node01 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@node02 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@node03 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@node04 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#
#ssh -i $CERT_PATH -J $PROXY lmancuso@device1 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device2 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device3 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device4 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device5 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device6 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device7 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device8 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device9 "cd federated-learning/Client/snapshots; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device10 "cd federated-learning/Client/snapshots; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device11 "cd federated-learning/Client/snapshots; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device12 "cd federated-learning/Client/snapshots; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device13 "cd federated-learning/Client/snapshots; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device14 "cd federated-learning/Client/snapshots; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device15 "cd federated-learning/Client/snapshots; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device16 "cd federated-learning/Client/snapshots; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device17 "cd federated-learning/Client/snapshots; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device18 "cd federated-learning/Client/snapshots; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device19 "cd federated-learning/Client/snapshots; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device20 "cd federated-learning/Client/snapshots; rm -rfv ./*"