PROXY="lmancuso@130.192.137.199"
CERT_PATH="/home/lore/Scaricati/mancuso_federated"

#ssh -i $CERT_PATH -J $PROXY lmancuso@coordinator "cd /mnt/dataset ; mv subset0 subset"

#ssh -i $CERT_PATH -J $PROXY lmancuso@node01 "cd /mnt/dataset ; mv subset01 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@node02 "cd /mnt/dataset ; mv subset02 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@node03 "cd /mnt/dataset ; mv subset03 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@node04 "cd /mnt/dataset ; mv subset04 subset"

ssh -i $CERT_PATH -J $PROXY lmancuso@device1 "cd /home/lmancuso/dataset ; mv subset05 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device2 "cd /home/lmancuso/dataset ; mv subset06 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device3 "cd /home/lmancuso/dataset ; mv subset07 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device4 "cd /home/lmancuso/dataset ; mv subset08 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device5 "cd /home/lmancuso/dataset ; mv subset09 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device6 "cd /home/lmancuso/dataset ; mv subset10 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device7 "cd /home/lmancuso/dataset ; mv subset11 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device8 "cd /home/lmancuso/dataset ; mv subset12 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device9 "cd /home/lmancuso/dataset ; mv subset13 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device10 "cd /home/lmancuso/dataset ; mv subset14 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device11 "cd /home/lmancuso/dataset ; mv subset15 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device12 "cd /home/lmancuso/dataset ; mv subset16 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device13 "cd /home/lmancuso/dataset ; mv subset17 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device14 "cd /home/lmancuso/dataset ; mv subset18 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device15 "cd /home/lmancuso/dataset ; mv subset19 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device16 "cd /home/lmancuso/dataset ; mv subset20 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device17 "cd /home/lmancuso/dataset ; mv subset21 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device18 "cd /home/lmancuso/dataset ; mv subset22 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device19 "cd /home/lmancuso/dataset ; mv subset23 subset"
ssh -i $CERT_PATH -J $PROXY lmancuso@device20 "cd /home/lmancuso/dataset ; mv subset24 subset"
