#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@coordinator:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/coordinator-progresses
#
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@node01:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/node01-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@node02:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/node02-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@node03:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/node03-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@node04:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/node04-progresses
#
##rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@node05:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/node05-Adam-01_progresses
#
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device1:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device1-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device2:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device2-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device3:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device3-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device4:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device4-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device5:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device5-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device6:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device6-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device7:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device7-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device8:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device8-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device9:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device9-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device10:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device10-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device11:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device11-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device12:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device12-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device13:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device13-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device14:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device14-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device15:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device15-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device16:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device16-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device17:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device17-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device18:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device18-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device19:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device19-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device20:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/24_nodes_sync/device20-progresses